azat/urls.py
from django.conf.urls import url
from . import views, api_views

app_name = 'azat'
urlpatterns = [
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),  # root
    url(r'^test/', views.test, name='test'),  # test
    url(r'^user/(?P<id>\w{0,30})/$', views.user_posts, name='user_posts'),
    url(r'^post/(?P<post_id>\w{0,30})/$', views.post, name='post'),
    url(r'^category/(?P<category_id>\w{0,30})/$', views.category_posts, name='category_posts'),
    url(r'^orders/', views.orders, name='orders'),
    url(r'^carts/(?P<order_id>[0-9]+)$', views.carts, name='carts'),
    url(r'^export/csv/$', views.export_orders_csv, name='export_orders_csv'),
    #url(r'^search/', include('haystack.urls')),
    #url(r'^counter/ajax/hit/$', update_hit_count_ajax, name='hitcount_update_ajax'),
    #url(r'^identicon/', include(django_pydenticon.urls.get_patterns())),

    # API
    url(r'^api/categories/$', api_views.categories, name='categories'),
    url(r'^api/countries/$', api_views.countries, name='countries'),
    url(r'^api/regions/$', api_views.regions, name='regions'),
    url(r'^api/register/$', api_views.create_user, name='create_user'),
    url(r'^api/login/$', api_views.login, name='login'),
    url(r'^api/category/(?P<post_type>[0-9]+)/posts/$', api_views.posts, name='posts'),  # if type = 0 show all posts
    url(r'^api/user/(?P<user_id>[0-9]+)/posts/$', api_views.user_posts, name='api_user_posts'),
    url(r'^api/post/(?P<post_id>[0-9]+)/hitcount/$', api_views.post_hitcount, name='post_hitcount'),
    url(r'^api/posts/search/$', api_views.search_post, name='search_post'),  # if type = 0 search in all posts
    url(r'^api/posts/create/$', api_views.create_post, name='create_post'),
    url(r'^api/post/(?P<post_id>[0-9]+)/$', api_views.post_detail, name='post_detail'),
    url(r'^api/user/(?P<user_id>[0-9]+)/orders/$', api_views.user_orders, name='api_user_orders'),
    url(r'^api/orders/(?P<order_id>[0-9]+)/items/$', api_views.api_order_items, name='api_order_items'),
    url(r'^api/orders/create/$', api_views.create_order, name='api_create_order'),
    url(r'^api/orders/(?P<order_id>[0-9]+)/status/(?P<status>[0-9]+)$', api_views.update_order, name='api_update_order'),
    url(r'^api/order/(?P<order_id>[0-9]+)/item/add/$', api_views.add_item, name='api_add_item'),
    # url(r'^api/post/(?P<post_id>[0-9]+)/images/$', api_views.save_images, name='save_images'),  # todo
    # url(r'^api/user/(?P<user_id>[0-9]+)/profile/image/$', api_views.save_profile_image, name='save_profile_image'),  # todo
    # url(r'^api/post/(?P<post_id>[0-9]+)/$', api_views.update_post, name='update_post'),  # todo
    # url(r'^api/post/(?P<post_id>[0-9]+)/$', api_views.delete_post, name='delete_post'),  # todo
    # url(r'^api/user/(?P<user_id>[0-9]+)/profile/$', api_views.edit_profile, name='edit_profile'),  # todo
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^azat/', include('azat.urls')),
    url(r'^arzymo/', include('arzymo.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sell/', include('sell.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

azat/models.py
from django.db import models
from django.contrib.auth.models import User
from imagekit import ImageSpec
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, ResizeToFit, Adjust
from mptt.models import MPTTModel, TreeForeignKey
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']


class Country(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=10)
    phone_code = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Region(models.Model):
    name = models.CharField(max_length=50)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=50)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100, null=True)
    content = models.CharField(max_length=4096)
    user = models.ForeignKey(User, default='', related_name='posts', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='category_posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    status = models.IntegerField(default=0, null=True)
    hitcount = models.IntegerField(default=0, null=True)
    type = models.IntegerField(default=0, null=True)  # post type or category type
    # statusChangeDate = models.DateTimeField('change date')
    # actionType = models.IntegerField(default=0)
    # phone = models.CharField(max_length=30)
    # location = models.ForeignKey(Location, on_delete=models.CASCADE)

    def __str__(self):
        return self.content


class Image(models.Model):
    reindex_related = ('post',)
    post = models.ForeignKey(Post, related_name='images', on_delete=models.CASCADE)
    original_image = ProcessedImageField(upload_to='post_images',
                                         default='',
                                         processors=[ResizeToFit(640, 640)],
                                         format='JPEG',
                                         options={'quality': 75})
    image_main_page = ImageSpecField(source='original_image',
                                     processors=[ResizeToFill(225, 180),
                                                 Adjust(contrast=1.2, sharpness=1.1)],
                                     format='JPEG',
                                     options={'quality': 60})
    image_post_page = ImageSpecField(source='original_image',
                                     processors=[ResizeToFit(640, 640),
                                                 Adjust(contrast=1.2, sharpness=1.1)],
                                     format='JPEG',
                                     options={'quality': 75})


def identicon_url(source, size):
        return '/identicon/image/' + source + '.png?w=' + size + '&h=' + size


class Thumbnail(ImageSpec):
    processors = [ResizeToFill(30, 30), Adjust(contrast=1.2, sharpness=1.1)]
    format = 'JPEG'
    options = {'quality': 80}


class Like(models.Model):
    user = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True)
    username = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    password_hash = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=40, null=True)
    api_key = models.CharField(max_length=50, null=True)
    status = models.IntegerField(default=0)
    created_at = models.DateTimeField(null=True)
    gcm_registration_id = models.TextField
    displayed_name = models.CharField(max_length=60, default='', blank=True)
    avatar_original_image = ProcessedImageField(upload_to='avatars',
                                                default='',
                                                processors=[ResizeToFit(480, 480)],
                                                format='JPEG',
                                                blank=True,
                                                options={'quality': 75})
    profile_image = ProcessedImageField(upload_to='profile',
                                        default='',
                                        processors=[ResizeToFill(300, 300)],
                                        format='JPEG',
                                        blank=True,
                                        options={'quality': 60})

    def avatar_30(self):
        if self.avatar_original_image:
            avatar = Thumbnail(source=self.avatar_original_image)
            return '/media/' + avatar.cachefile_name
        else:
            #set 10px less size since 5px padding. See settings for PYDENTICON_PADDING
            return identicon_url(self.user.username, '30')

    def __str__(self):
        return self.user.username


class Order(models.Model):
    user = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    status = models.IntegerField(default=0)  #0-bucket 1-order 2-done 3-canceled
    creation_date = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return str(self.pk)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order_items', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    amount = models.IntegerField(default=1)
    sum = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return str(self.pk)


class ChatRoom(models.Model):
    name = models.CharField(max_length=200)
    create_at = models.DateTimeField('date created')

    def __str__(self):
        return self.name


class Chat(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    idUser1 = models.IntegerField(default=0)
    idUser2 = models.IntegerField(default=0)
    isActive1 = models.BooleanField(default=1)
    isActive2 = models.BooleanField(default=1)
    deleted_at1 = models.DateTimeField(blank=True)
    deleted_at2 = models.DateTimeField(blank=True)
    created_at = models.DateTimeField('date created')


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    message = models.TextField
    created_at = models.DateTimeField('date created')


# RECEIVERS
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        Token.objects.get_or_create(user=instance)


# Delete image files on image instance deletion.
@receiver(post_delete, sender=Image)
def image_post_delete_handler(sender, **kwargs):
    image = kwargs['instance']
    storage, path = image.original_image.storage, image.original_image.path
    storage.delete(path)


# Create API token on user creation.
@receiver(post_save, sender=User)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.get_or_create(user=instance)

azat/views.py
import csv
from django.shortcuts import render
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404, HttpResponse
from .models import Post, Image, Category, Order, OrderItem


def index(request):
    return render(request, 'azat/index.html', )


def post(request, post_id=""):
    if post_id:
        # Show a post
        post = Post.objects.get(pk=post_id)
        images = Image.objects.filter(post=post)

        return render(request, 'azat/post.html', {'post': post, 'images': images})


def user_posts(request, id=""):
    if id:
        # Show a profile
        try:
            user = User.objects.get(pk=id)
        except User.DoesNotExist:
            raise Http404
        posts_list = Post.objects.filter(user=user.id)
        paginator = Paginator(posts_list, 8)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)

        images = []
        no_image_posts = []
        for post in posts_list:
            images.extend(list(Image.objects.filter(post=post).order_by('id')[:1]))
            if not Image.objects.filter(post=post):
                no_image_posts.append(post)

        return render(request, 'azat/user.html', {'user': user, 'posts': posts, 'images': images, 'no_image_posts': no_image_posts})


def category_posts(request, category_id=""):
    if category_id:
        # Show posts in category
        try:
            category = Category.objects.get(id=category_id)
            # Family is category with subcategories
            family = category.get_descendants(include_self=True)
        except Category.DoesNotExist:
            raise Http404
        posts_list = Post.objects.filter(category__in=family)
        paginator = Paginator(posts_list, 8)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)
        images = []
        no_image_posts = []
        for post in posts_list:
            images.extend(list(Image.objects.filter(post=post).order_by('id')[:1]))
            if not Image.objects.filter(post=post):
                no_image_posts.append(post)

        return render(request, 'azat/category.html', {'category': category, 'posts': posts, 'images': images, 'no_image_posts': no_image_posts})


def orders(request):
    orders_list = Order.objects.filter(status=1).order_by('-creation_date')[:1000]
    context = {'orders_list': orders_list}
    return render(request, 'azat/orders.html', context)


def carts(request, order_id):
    items = OrderItem.objects.filter(order__pk=order_id).order_by('-id')[:1000]
    context = {'carts_list': items}
    return render(request, 'azat/carts.html', context)


def export_orders_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="orders.csv"'
    writer = csv.writer(response)
    writer.writerow(['Номер заказа', 'Клиент', 'Id товара', 'Товар', 'Количество', 'Сумма', 'Дата', 'Статус'])
    orders_list = Order.objects.all().values_list('pk', 'owner', 'post', 'post', 'amount', 'sum', 'creation_date',
                                                  'status')
    for order in orders_list:
        writer.writerow(order)

    return response


def test(request):
    posts_list = Post.objects.all().order_by('-creation_date')  # [:100]
    # Get 1st image of each post and set no_image_post flag if no image found.
    images = []
    no_image_posts = []
    for post in posts_list:
        images.extend(list(Image.objects.filter(post=post).order_by('id')[:1]))
        if not Image.objects.filter(post=post):
            no_image_posts.append(post)

    paginator = Paginator(posts_list, 8)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'azat/test.html',
                  {'next_url': '/',
                   'posts': posts, 'images': images, 'no_image_posts': no_image_posts})

azat/templates/azat/base.html
<!DOCTYPE html>
<html>
{% load static %}
{% block head %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ananas.io | Мобильная торговля</title>
    <link rel="stylesheet" type="text/css" href="{% static 'azat/css/foundation.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'azat/css/ananas.css' %}">
    <script src="{% static 'azat/js/vendor/modernizr.js' %}"></script>
</head>
{% endblock %}
<body>

{% block header %}
    <header>
        <section class="row collapse">
            <div class="large-2 columns">
                <h1><a href="{% url 'azat:index' %}">Azat</a></h1>
            </div>
              <div class="large-10 columns">
                  <form method="get" action="/search">
                      <div class="search_box row collapse">
                          <div class="small-10 columns">
                            <input id="id_q" name="q" type="search" placeholder="Поиск" value="{{ query }}">
                          </div>
                          <div class="small-2 columns">
                            <input type="submit" class="button postfix" value="Поиск">
                          </div>
                      </div>
                  </form>
              </div>
        </section>
    </header>
{% endblock %}

    <div class="mainWrapper">
        <div class="wrapper">
            {% block flash %}
            {% if auth_form.non_field_errors or user_form.non_field_errors or Karma_form.errors %}
            <div class="flash error">
                {{ auth_form.non_field_errors }}
                {{ user_form.non_field_errors }}
                {{ Mozan_form.content.errors }}
            </div>
            {% endif %}
            {% if notice %}
            <div class="flash notice">
                {{ notice }}
            </div>
            {% endif %}
            {% endblock %}

{% block content %}

{% endblock %}
        </div>
    </div>
 <footer>
        <div class="row collapse">
          <div class="large-6 columns">
            <p>info@ananas.io</p>
          </div>
          <div class="large-6 columns">
            <ul class="inline-list right">
              <li><a href="{% url 'azat:orders' %}">Заказы</a></li>
              <li><a href="#">О нас</a></li>
              <li><a href="#">Соглашение о пользовании</a></li>
            </ul>
          </div>
        </div>
 </footer>
</body>
</html>

azat/templates/azat/carts.html
{% extends "azat/base.html" %}
{% load static %}

{% block content %}
{% if auth_form.non_field_errors or user_form.non_field_errors %}
<div class="flash error">
    {{ auth_form.non_field_errors }}
    {{ user_form.non_field_errors }}
</div>
{% endif %}
<section>
    <div class="row panel">
      <div class="large-12 columns">
          <form method="get" action="/search">
              <div class="row collapse">
                  <div class="small-10 columns">
                  </div>
                  <div class="small-2 columns">
                      <a href="{% url 'azat:export_orders_csv' %}"><img src="{% static 'azat/img/excel.png' %}"/></a>
                  </div>
              </div>
          </form>
          <div class="row">
     <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Номер заказа</th>
                <th>Клиент</th>
                <th>Id Продукта</th>
                <th>Продукт</th>
                <th>Количество</th>
                <th>Сумма</th>
            </tr>
        </thead>
        <tbody>
        {% for item in carts_list %}
            <tr>
                <td>{{ item.order.pk }}</td>
                <td>{{ item.order.user }}</td>
                <td>{{ item.post.pk }}</td>
                <td>{{ item.post.title }}</td>
                <td>{{ item.amount }}</td>
                <td>{{ item.sum }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
      </div>
    </div>
</section>


{% endblock %}

azat/templates/azat/category.html
{% extends "azat/base.html" %}

{% block content %}
<section class="hero-content">
    <div class="row panel">
        {% if category.get_ancestors %}
            {% for parent in category.get_ancestors %}
                    <a class="" href="/category/{{ parent.id }}">{{ parent.name }}</a> &darr;
            {% endfor %}
        {% endif %}
        <h3>{{ category.name }}</h3>
        {% if category.get_children %}
            {% for child in category.get_children %}
                    <a class="button" href="/category/{{ child.id }}">{{ child.name }}</a>
            {% endfor %}
        {% endif %}
    </div>
    <div class="row panel posts collapse">
        {% for post in posts %}
        <div class="postWrapper small-5 large-3 medium-3 column{% if forloop.last %} end {% endif %}">
            <a class="th" href="{% url 'azat:post' post.pk %}">
            {% for image in images %}
                {% if image.post == post  %}
                    <img class="postImage" src="{{ image.image_main_page.url }}">
                {% endif %}
            {% endfor %}
            {% if post in no_image_posts %}
                <img class="postImage" src="/media/default/no_image_main_page.jpg">
            {% endif %}
            </a>
            <div class="postMeta">
                <div class="postDescription">
                    {{ post.content }}
                </div>
                <div class="postBadges">
                    <span class="hit-count">20</span>
                    <span class="price">50</span>
                </div>
                <div class="postAuthor">
                    <a href="{% url 'azat:user_posts' post.user.id %}">
                        <img class="avatar" src="{{ post.user.profile.avatar_30 }}">
                        <span class="name">{% firstof post.user.profile.displayed_name post.user.username %}</span>
                    </a>
                    <a href="{% url 'azat:category_posts' post.category.id %}">
                        <div class="category"> {{ post.category }}</div>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% if posts.has_previous or posts.has_next %}
            <div class="clear_both">
                <span class="current">
                   Страница {{ posts.number }} из {{ posts.paginator.num_pages }}
                </span>
                {% if posts.has_previous %}<a href="?q={{ query }}&amp;page={{ posts.previous_page_number }}">{% endif %}&laquo; Предыдущая{% if posts.has_previous %}</a>{% endif %}
                |
                {% if posts.has_next %}<a href="?q={{ query }}&amp;page={{ posts.next_page_number }}">{% endif %}Следующая &raquo;{% if posts.has_next %}</a>{% endif %}
            </div>
        {% endif %}
    </div>
</section>
{% endblock %}

azat/templates/azat/index.html
{% extends "azat/base.html" %}
{% load static %}

{% block header %}
    <header class="home">
        <div class="wrapper">
            <h1><a >Azat</a></h1>
            <h3>товары</h3>
        </div>
    </header>
{% endblock %}

{% block content %}
{% if auth_form.non_field_errors or user_form.non_field_errors %}
<div class="flash error">
    {{ auth_form.non_field_errors }}
    {{ user_form.non_field_errors }}
</div>
{% endif %}

<section>
    <div class="row panel">
      <div class="large-12 columns">
          <form method="get" action="/search">
              <div class="row collapse">
                  <div class="small-10 columns">
                    <input id="id_q" name="q" type="search" placeholder="Поиск">
                  </div>
                  <div class="small-2 columns">
                    <input type="submit" class="button postfix" value="Поиск">
                  </div>
              </div>
          </form>
          <div class="row">
    <div class="column small-centered large-8">
      <ul class="small-block-grid-2 large-block-grid-3">
        <li><a class="icon button info" href="{% url 'azat:category_posts' 1 %}"><img src="{% static 'azat/img/food_icon.png' %}" />Продукты-питания</a></li>
        <li><a class="icon button info" href="{% url 'azat:category_posts' 2 %}"><img src="{% static 'azat/img/soap_icon.png' %}"/>Мыло моющие средства</a></li>
        <li><a class="icon button info" href="{% url 'azat:category_posts' 3 %}"><img src="{% static 'azat/img/ice_tea_icon.png' %}"/>Напитки</a></li>
        <li><a class="icon button info" href="{% url 'azat:category_posts' 5 %}"><img src="{% static 'azat/img/drinks_icon.png' %}"/>Спиртные напитки</a></li>
        <li><a class="icon button info" href="{% url 'azat:category_posts' 4 %}"><img src="{% static 'azat/img/cigarette-smoking.png' %}"/>Табачные изделия</a></li>
        <li><a class="icon button info" href="{% url 'azat:category_posts' 6 %}"><img src="{% static 'azat/img/shopping_icon.png' %}"/>Другие товары</a></li>
      </ul>
    </div>
    </div>
      </div>
    </div>
</section>


{% endblock %}

azat/templates/azat/orders.html
{% extends "azat/base.html" %}
{% load static %}

{% block content %}
{% if auth_form.non_field_errors or user_form.non_field_errors %}
<div class="flash error">
    {{ auth_form.non_field_errors }}
    {{ user_form.non_field_errors }}
</div>
{% endif %}
<section>
    <div class="row panel">
      <div class="large-12 columns">
          <form method="get" action="/search">
              <div class="row collapse">
                  <div class="small-10 columns">
                  </div>
                  <div class="small-2 columns">
                      <a href="{% url 'azat:export_orders_csv' %}"><img src="{% static 'azat/img/excel.png' %}"/></a>
                  </div>
              </div>
          </form>
          <div class="row">
     <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Номер заказа</th>
                <th>Клиент</th>
                <th>Сумма</th>
                <th>Дата</th>
                <th>Статус</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders_list %}
            <tr>
                <td><a href="{% url 'azat:carts' order.pk %}">{{ order.pk }}</a></td>
                <td>{{ order.user }}</td>
                <td>{{ order.total }}</td>
                <td>{{ order.creation_date }}</td>
                <td>{{ order.status }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
      </div>
    </div>
</section>


{% endblock %}

azat/templates/azat/post.html
{% extends "azat/base.html" %}

{% block content %}
<section class="hero-content">
    <div class="post row ">
        <div class="postWrapper ">
            {% for image in images  %}
                <img class="postImage" src="{{ image.image_post_page.url }}">
            {% endfor %}
            {% if not images %}
                <img class="postImage" src="/media/default/no_image.jpg">
            {% endif %}
            <div class="postMeta">
                <div class="postDescription">
                    {{ post.content }}
                </div>
                <div class="postBadges">
                    <span class="hit-count">20</span>
                    <span class="price">400</span>
                </div>
                <div class="postAuthor">
                    <a href="{% url 'azat:user_posts' post.user.id %}">
                        <img class="avatar" src="{{ post.user.profile.avatar_30 }}">
                        <span class="name">{% firstof post.user.profile.displayed_name post.user.username %}</span>
                    </a>
                    <a href="{% url 'azat:category_posts' post.category.id %}">
                        <div class="category"> {{ post.category }}</div>
                    </a>
                </div>

            </div>

        </div>
    </div>
</section>
{% endblock %}

azat/templates/azat/test.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

azat/templates/azat/user.html
{% extends "azat/base.html" %}

{% block content %}
<section class="hero-content">
    <div class="row panel">
        <h1>{{ user.profile.displayed_name }}</h1>

        <div class="userWrapper">
            <a class="th" href="/users/{{ user.username }}">
                <img class="avatar" src="{{ user.profile.avatar_30 }}">
                <span class="name">{% firstof user.profile.displayed_name user.username %}</span>
            </a>
            <p>Количество постов: {{ posts.count }}</p>

            <p class="spacing">Репутация: {{ user.profile.follows.all.count }} </p>

            <p class="spacing">Отзывы: {{ user.profile.followed_by.all.count }} </p>
            {% if follow %}
            <form action="/follow" method="post">
                {% csrf_token %}
                <input type="hidden" name="follow" value="{{ user.id }}">
                <input type="submit" value="Follow">
            </form>
            {% endif %}
        </div>
    </div>

    <div class="row panel posts collapse">
        {% for post in posts %}
        <div class="postWrapper small-5 large-3 medium-3 column{% if forloop.last %} end{% endif %}">
            <a class="th" href="{% url 'azat:post' post.pk %}">
            {% for image in images %}
                {% if image.post == post  %}
                    <img class="postImage" src="{{ image.image_main_page.url }}">
                {% endif %}
            {% endfor %}
            {% if post in no_image_posts %}
                <img class="postImage" src="/media/default/no_image_main_page.jpg">
            {% endif %}
            </a>
            <div class="postMeta">
                <div class="postDescription">
                    {{ post.content }}
                </div>
                <div class="postBadges">
                    <span class="hit-count">12</span>
                    <span class="price">22</span>
                </div>
                <div class="postAuthor">
                        <a href="{% url 'azat:category_posts' post.category.id %}">
                            <div class="category"> {{ post.category }}</div>
                        </a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% if posts.has_previous or posts.has_next %}
            <div class="clear_both">
                <span class="current">
                   Страница {{ posts.number }} из {{ posts.paginator.num_pages }}
                </span>
                {% if posts.has_previous %}<a href="?q={{ query }}&amp;page={{ posts.previous_page_number }}">{% endif %}&laquo; Предыдущая{% if posts.has_previous %}</a>{% endif %}
                |
                {% if posts.has_next %}<a href="?q={{ query }}&amp;page={{ posts.next_page_number }}">{% endif %}Следующая &raquo;{% if posts.has_next %}</a>{% endif %}
            </div>
        {% endif %}
    </div>
</section>
{% endblock %}